### ISSUE TITLE
conda env broken

### ISSUE THREAD

**Issue by cehbrecht** [ESGF/esgf-compute-cert#6]
I wanted to install the compute test suite using conda but the environment seems to be broken (dependency issues). I just copy the error messages:

```
$ conda env create -f environment.yaml
Collecting package metadata: done
Solving environment: failed

ResolvePackageNotFound:
  - curl=7.49.1
  - cdms2=3.1.0 -> esmf[version='>=7.1.*']
  - cdms2=3.1.0 -> esmpy[version='>=7.1.*']
```

I also tried the conda package as recommend in the readme:
```
$ conda create -n esgf-compute-cert -c conda-forge -c cdat esgf-compute-cert
$ conda activate esgf-compute-cert
$ cwt-cert --host https://aims2.llnl.gov/wps
Errors:

/opt/miniconda3/envs/esgf-compute-cert/lib/python2.7/site-packages/cdtime/compreltime.py:2: in <module>
    from . import _cdtime
E   ImportError: libjasper.so.1: cannot open shared object file: No such file or directory

/opt/miniconda3/envs/esgf-compute-cert/lib/python2.7/site-packages/cdms2/__init__.py:7: in <module>
    from . import myproxy_logon  # noqa
E   ImportError: cannot import name myproxy_logon
```

**Comment by cehbrecht** [comment]
You may setup a cron job on travis CI to check the test-suite.

**Comment by jasonb5** [comment]
> You may setup a cron job on travis CI to check the test-suite.

Our CI was using a cached version

**Comment by jasonb5** [comment]
The CDMS2 package broke and we're working on updating the environment file with a correct working version.

**Comment by jasonb5** [comment]
Removed the environment file, letting conda figure out the dependencies should be the preferred method of installation.
